HINT_LOCATIONS = {
    8110: {"id": 8110, "area": "Undead Asylum", "original_text": "Exchange"},
    1200: {"id": 1200, "area": "Firelink Shrine", "original_text": "Path ahead"},
    1201: {"id": 1201, "area": "Firelink Shrine", "original_text": "Here!"},
    1202: {"id": 1202, "area": "Undead Burg", "original_text": "Imminent Merchant"},
    1100: {"id": 1100, "area": "Undead Burg", "original_text": "Imminent drake..."},
    1104: {"id": 1104, "area": "Undead Burg", "original_text": "Jumping off ahead"},
    1101: {"id": 1101, "area": "Undead Burg", "original_text": "Prisoner ahead"},
    1102: {"id": 1102, "area": "Undead Parish", "original_text": "Prisoner ahead"},
    1103: {"id": 1103, "area": "Undead Parish", "original_text": "Blacksmith ahead"},
    2000: {"id": 2000, "area": "Darkroot Garden", "original_text": "Follow the shining flowers"},
    2001: {"id": 2001, "area": "Darkroot Garden", "original_text": "Are the trees moving?"},
    1003: {"id": 1003, "area": "Depths", "original_text": "I can't take this"},
    1000: {"id": 1000, "area": "Depths", "original_text": "Try sliding down"},
    1002: {"id": 1002, "area": "Depths", "original_text": "Imminent shortcut"},
    1001: {"id": 1001, "area": "Depths", "original_text": "Weakness: Head"},
    4001: {"id": 4001, "area": "Blighttown", "original_text": "Path Ahead"},
    4000: {"id": 4000, "area": "Quelaag's Domain", "original_text": "Illusory Wall"},
    3001: {"id": 3001, "area": "The Catacombs", "original_text": "Try divine"},
    3000: {"id": 3000, "area": "The Catacombs", "original_text": "Treasure"},
    3002: {"id": 3002, "area": "The Catacombs", "original_text": "Blacksmith ahead"},
    3003: {"id": 3003, "area": "The Catacombs", "original_text": "Liar"},
    3004: {"id": 3004, "area": "The Catacombs", "original_text": "Up"},
    3100: {"id": 3100, "area": "The Catacombs", "original_text": "Shortcut ahead"},
    6000: {"id": 6000, "area": "New Londo Ruins", "original_text": "Need Curses"},
    6002: {"id": 6002, "area": "New Londo Ruins", "original_text": "Imminent jumping off..."},
    6001: {"id": 6001, "area": "New Londo Ruins", "original_text": "Need Covenant"},
    5000: {"id": 5000, "area": "Sen's Fortress", "original_text": "Prisoner ahead"},
    5101: {"id": 5101, "area": "Anor Londo", "original_text": "Path ahead"},
    5100: {"id": 5100, "area": "Anor Londo", "original_text": "Try Projectile"},
    6003: {"id": 6003, "area": "Valley of Drakes", "original_text": "Ring Ahead"},
    4100: {"id": 4100, "area": "Demon Ruins", "original_text": "Safe Zone Ahead"},
    7001: {"id": 7001, "area": "Crystal Cave", "original_text": "Path Ahead"}
}

TRASH_HINTS = {
    "Lautrec should not be trusted",
    "Do NOT feed the giant snake",
    "Clod was here",
    "You sorry Fool, you could not be the chosen one",
    "Bearer of the curse, seek seek lest...",
    "Chosen undead, please remember to link the fires",
    "Ashen one, the trees here are very treacherous",
    "Remember to check in on your local crestfallen friends",
    "Humanity increases your item find...",
    "Majula is on the way of the Chosen Undead",
    "New Londo is very spooky",
    "Please be kind to the local dog population",
    "Would Giant Dad be proud right now",
    "Chosen Undead seek a way out",
    "Consider visiting your local Poison Swamp",
    "Please avoid standing in the lava without protection",
    "Help control the local spider wife population",
    "Ring two bells to win a prize (giant snake)",
    "Local clerics should head to the catacombs for treasure!",
    "Tales tell of a gigantic king of rats, somewhere under the city",
    "Pyromancy is lit"
}

USEFUL_LOCATIONS = {
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Bed of Chaos": {"location_id": 2580, "hint_text": "Bed of Chaos guards {1}"},
    "Manus": {"location_id": 2700, "hint_text": "Manus, Father of the Abyss guards {1}"},
    "Kalameet": {"location_id": 2710, "hint_text": "Kalameet the big dragon guards {1}"},
    "4 Kings": {"location_id": 2630, "hint_text": "The Four Kings guard {1}"},
    "Nito": {"location_id": 2560, "hint_text": "Gravelord Nito guards {1}"},
    "Ash Lake Hydra": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
    "Sif": {"location_id": 2540, "hint_text": "Great Wolf Sif guards {1}"},
}